import { PublicDocument, PublicPageShell } from '@/components/marketing/PublicPageShell';

export function PrivacyPolicyPage(){return <PublicPageShell label="Trust / Privacy" title="Your workspace starts local." intro="This notice describes the behavior implemented in the current Panvas codebase. Optional services are separated from the local workspace and may require release configuration." aside={<>CURRENT PRODUCT NOTICE<br/>Updated 7 September 2026<br/>Pre-release software</>}>
  <PublicDocument>
    <section><span className="pp-section-index">01</span><div><h2>Local workspace data</h2><p>On Windows desktop, Panvas stores the authoritative workspace in a local filesystem directory. The browser build stores workspace records in origin-scoped IndexedDB. Notes, drawings, canvases and imported assets do not need a Panvas account or network connection for ordinary local use.</p><p>Browser storage remains subject to the browser and device’s storage controls. Exported backups and files remain under your control.</p></div></section>
    <section><span className="pp-section-index">02</span><div><h2>Optional Google Drive sync</h2><p>Google Drive synchronization is implemented behind explicit release flags and remains disabled by default while runtime certification is completed. When enabled and connected by you, Panvas communicates directly with Google APIs using the limited <code>drive.file</code> scope.</p><p>The browser keeps the Google access token in memory. The desktop app stores Google tokens using Electron’s operating-system-backed secure storage and does not expose them to the renderer. Disconnecting revokes or removes the locally held authorization where supported.</p></div></section>
    <section><span className="pp-section-index">03</span><div><h2>Authentication</h2><p>Local workspace use does not require an account. Development or configured web builds can offer Supabase authentication using email/password or Google and GitHub OAuth. In those builds, the authentication provider processes account identifiers, session information and any profile information returned by the selected provider.</p><p>Signing out does not delete local workspace records.</p></div></section>
    <section><span className="pp-section-index">04</span><div><h2>Analytics and network access</h2><p>Product analytics is off in ordinary workspace builds. PostHog analytics can initialize only when both the analytics flag and marketing-only build flag are enabled and a key is configured. Automatic interaction capture and automatic pageview capture are disabled in code.</p><p>Network access may also occur when you choose authentication or Google Drive features, or when the application loads third-party resources required by those configured features.</p></div></section>
    <section><span className="pp-section-index">05</span><div><h2>Your controls</h2><p>You can continue using a local workspace without enabling Google Drive or authentication. You can disconnect Google Drive, sign out of an optional account, and manage or remove local files using the controls provided by your operating system or browser.</p><div className="pp-note">Account deletion procedures, production operator identity, legal contact details, and any server-side retention rules require human/legal confirmation before public release.</div></div></section>
  </PublicDocument>
</PublicPageShell>}
