import { PublicDocument, PublicPageShell } from '@/components/marketing/PublicPageShell';
import { PANVAS_RELEASE } from '@/components/marketing/releaseMetadata';

export function SecurityPage(){return <PublicPageShell label="Trust / Security" title="Security architecture." intro="Panvas reduces unnecessary data movement through a local-first design. This page documents controls visible in the repository and does not claim certification or absolute security." aside={<>ARCHITECTURE SNAPSHOT<br/>Local authority<br/>Optional network features</>}>
  <PublicDocument>
    <section><span className="pp-section-index">01</span><div><h2>Local-first boundary</h2><p>The Windows desktop build keeps its authoritative workspace in a local filesystem directory. The browser build uses origin-scoped IndexedDB. Ordinary editing does not require a hosted Panvas workspace service or an account.</p></div></section>
    <section><span className="pp-section-index">02</span><div><h2>Desktop and Electron</h2><p>The main application window enables context isolation, renderer sandboxing and web security while disabling Node integration. The preload bridge exposes named capabilities rather than general Node or filesystem access. Navigation and new-window requests are restricted to trusted renderer URLs or sent to the system browser.</p><p>Privileged workspace operations run through Electron IPC handlers with input validation and path checks. Automated integrity tests cover these boundaries.</p></div></section>
    <section><span className="pp-section-index">03</span><div><h2>Authentication and Google Drive</h2><p>Optional account authentication uses Supabase when configured; Panvas does not implement or describe the provider’s password hashing internals. Google Drive authorization requests only <code>drive.file</code>. Browser access tokens are memory-only, while desktop tokens require Electron secure storage. Cloud sync is opt-in, release-gated and disabled by default.</p></div></section>
    <section><span className="pp-section-index">04</span><div><h2>Content and imports</h2><p>Rich-text HTML passes through a sanitizer before insertion. PDF and backup workflows apply application-level validation, but imported files should still be treated as untrusted input. Diagnostic handling is designed to return bounded public errors and sanitize cloud-sync diagnostics.</p></div></section>
    <section><span className="pp-section-index">05</span><div><h2>Reporting a vulnerability</h2><p>Please use the repository’s private security reporting facility if available, or contact the maintainer through the address listed in the project metadata: <a href={PANVAS_RELEASE.project.creatorEmailUrl}>sksumitahmed007@gmail.com</a>. Avoid including sensitive workspace content in an initial report.</p><p>Response times and disclosure SLAs have not yet been formally published.</p></div></section>
  </PublicDocument>
</PublicPageShell>}
