import { PublicDocument, PublicPageShell } from '@/components/marketing/PublicPageShell';

export function TermsOfServicePage(){return <PublicPageShell label="Trust / Terms" title="Terms for the current preview." intro="Panvas is pre-release software. These concise product terms describe the current preview without inventing a legal entity, jurisdiction, or release commitment." aside={<>CURRENT PRODUCT NOTICE<br/>Updated 7 September 2026<br/>Human legal review pending</>}>
  <PublicDocument>
    <section><span className="pp-section-index">01</span><div><h2>Using Panvas</h2><p>Panvas provides local-first tools for notebooks, drawing, PDFs and visual canvases. You may use the local workspace without an account. Some optional or pre-release capabilities require configuration, an external provider, or a supported platform.</p></div></section>
    <section><span className="pp-section-index">02</span><div><h2>Your content and responsibilities</h2><p>You are responsible for the material you create, import, synchronize or export and for ensuring that you have permission to use it. Keep independent backups of important work, especially while Panvas remains in pre-release verification.</p></div></section>
    <section><span className="pp-section-index">03</span><div><h2>Optional services</h2><p>If you choose Google Drive or an authentication provider, that provider’s terms and privacy practices also apply. Availability of experimental, gated or preview features may change as testing continues.</p></div></section>
    <section><span className="pp-section-index">04</span><div><h2>Software status</h2><p>The current Windows and browser builds are pre-release software. Features may contain defects or change before a stable release. Published source-code licensing is governed by the license file in the repository once the project owner finalizes it.</p><div className="pp-note">A qualified reviewer must supply the operator identity, binding license terms, warranty and liability language, governing law, age requirements, termination rules and formal contact process. Those facts are intentionally not fabricated here.</div></div></section>
  </PublicDocument>
</PublicPageShell>}
