import React from 'react';
import { Bookmark, Check, ChevronRight, Code2, Image as ImageIcon, MessageCircle, Minus, Quote, Sigma, StickyNote, Table2 } from 'lucide-react';

export function NotebookBlockGallery() {
  return <section className="mt-12" aria-labelledby="block-gallery-heading"><div className="mb-4"><div id="block-gallery-heading" className="text-sm font-medium text-panvas-text-primary">Block type gallery</div><p className="mt-1 text-xs text-panvas-text-tertiary">Visual previews for the notebook blocks planned for the editor.</p></div><div className="grid gap-3 sm:grid-cols-2"><Preview title="Callout"><div className="rounded border-l-2 border-panvas-border-strong bg-panvas-bg-secondary px-3 py-2 text-xs text-panvas-text-secondary"><MessageCircle size={13} className="mr-1.5 inline" />Important context lives here.</div></Preview><Preview title="Code"><div className="rounded bg-panvas-bg-secondary p-2 font-mono text-2xs leading-5 text-panvas-text-secondary">const note = 'Panvas';</div></Preview><Preview title="Quote"><blockquote className="border-l-2 border-panvas-border-default pl-3 text-xs italic leading-5 text-panvas-text-secondary">“Make room for the thought.”</blockquote></Preview><Preview title="Checklist"><div className="space-y-1 text-xs text-panvas-text-secondary"><div><Check size={12} className="mr-1 inline" />Review sources</div><div className="text-panvas-text-tertiary">○ Draft outline</div></div></Preview><Preview title="Table"><div className="grid grid-cols-3 overflow-hidden rounded border border-panvas-border-subtle text-2xs"><Cell value="Name" head /><Cell value="Status" head /><Cell value="Owner" head /><Cell value="Notes" /><Cell value="Open" /><Cell value="You" /></div></Preview><Preview title="Image"><div className="flex h-16 items-center justify-center rounded border border-dashed border-panvas-border-default bg-panvas-bg-secondary text-2xs text-panvas-text-tertiary"><ImageIcon size={14} className="mr-1" />Image preview</div></Preview><Preview title="Gallery"><div className="grid grid-cols-3 gap-1"><span className="h-10 rounded bg-panvas-bg-secondary" /><span className="h-10 rounded bg-panvas-bg-active" /><span className="h-10 rounded bg-panvas-bg-secondary" /></div></Preview><Preview title="Bookmark"><div className="flex items-center gap-2 rounded border border-panvas-border-subtle p-2 text-xs"><Bookmark size={14} className="text-panvas-text-tertiary" /><div><div className="text-panvas-text-primary">Reference link</div><div className="text-2xs text-panvas-text-tertiary">example.com</div></div></div></Preview><Preview title="Equation"><div className="py-1 text-center font-serif text-base text-panvas-text-primary">E = mc²</div></Preview><Preview title="Divider"><div className="flex items-center gap-2 py-3"><span className="h-px flex-1 bg-panvas-border-subtle" /><Minus size={12} className="text-panvas-text-tertiary" /><span className="h-px flex-1 bg-panvas-border-subtle" /></div></Preview><Preview title="Toggle"><div className="flex items-center gap-1.5 text-xs text-panvas-text-secondary"><ChevronRight size={14} />Details can be expanded here.</div></Preview></div></section>;
}

function Preview({ title, children }: { title: string; children: React.ReactNode }) { return <article className="rounded-lg border border-panvas-border-subtle bg-panvas-bg-elevated p-3 transition-colors hover:border-panvas-border-default hover:bg-panvas-bg-secondary/30"><div className="mb-2 text-2xs font-medium uppercase tracking-[0.1em] text-panvas-text-tertiary">{title}</div>{children}</article>; }
function Cell({ value, head = false }: { value: string; head?: boolean }) { return <span className={`border-b border-r border-panvas-border-subtle px-1.5 py-1 ${head ? 'bg-panvas-bg-secondary text-panvas-text-secondary' : 'text-panvas-text-tertiary'}`}>{value}</span>; }
